import '../assets/globals.css'
import { Inter } from "@next/font/google";
import Head from "next/head";
import PageHeader from "../components/layout/header";
import PageFooter from "../components/layout/footer";

// Initialize `Inter` font
const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
})

export default function MyApp({ Component, pageProps }) {
    return (
        <div className={`${inter.variable} font-sans`}>
            <Head>
                <title>Sin-Tat&apos;s Personal Website | Full Stack Developer</title>
                <meta content="width=device-width, initial-scale=1" name="viewport" />
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <PageHeader />
            <Component {...pageProps} />
            <PageFooter />
        </div>
    )
}